import Head from "next/head";

import { GoBook } from "react-icons/go";

import React, { Component, useState } from "react";

import { Row, Col, Container, Button, Image } from "react-bootstrap";

const data = {
  2016: {
    image: "/image/home_left.jpg",
    p: "We provide the best Beard oil all over the world. We are the worldd best store for Beard Oil. You can buy our product without any hegitation because we always consus about our product quality and always maintain it properly so your can trust and this is our main goal we belive that Some of our customer say’s that they trust us and buy our product without any hagitation because they belive us and always happy",
  },
  2017: {
    image: "/image/home_right.jpg",
    p: "We provide the best Beard oil all over the world. We are the worldd best store for Beard Oil. You can buy our product without any hegitation because we always consus about our product quality and always maintain it properly so your can trust and this is our main goal we belive that Some of our customer say’s that they trust us and buy our product without any hagitation because they belive us and always happy",
  },
  2018: {
    image: "/image/leftTop.jpg",
    p: "We provide the best Beard oil all over the world. We are the worldd best store for Beard Oil. You can buy our product without any hegitation because we always consus about our product quality and always maintain it properly so your can trust and this is our main goal we belive that Some of our customer say’s that they trust us and buy our product without any hagitation because they belive us and always happy",
  },
  2019: {
    image: "/image/rigthDown.jpg",
    p: "We provide the best Beard oil all over the world. We are the worldd best store for Beard Oil. You can buy our product without any hegitation because we always consus about our product quality and always maintain it properly so your can trust and this is our main goal we belive that Some of our customer say’s that they trust us and buy our product without any hagitation because they belive us and always happy",
  },
  2020: {
    image: "/image/home_left.jpg",
    p: "We provide the best Beard oil all over the world. We are the worldd best store for Beard Oil. You can buy our product without any hegitation because we always consus about our product quality and always maintain it properly so your can trust and this is our main goal we belive that Some of our customer say’s that they trust us and buy our product without any hagitation because they belive us and always happy",
  },
};
export default function About() {
  const [year, setYear] = useState(Object.keys(data)[0]);
  return (
    <div>
      <Head>
        <title>Nail Nail Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ background: "#ECBD99" }}>
        <Container>
          <Row>
            <Col
              style={{
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
              }}
            >
              <h1
                style={{
                  color: "#fff",
                  fontSize: "50px",
                  fontWeight: 700,
                }}
              >
                About Us
              </h1>
              <div>
                <a href="/"> Home</a> {">"} About Us
              </div>
            </Col>
            <Col
              style={{
                display: "flex",
                justifyContent: "center",
              }}
            >
              <Image
                src="/image/cbd_oil.png"
                width={600}
                height={353}
                layout="responsive"
              />
            </Col>
          </Row>
        </Container>
      </div>

      <Container style={{ marginTop: 40 }}>
        <Row>
          <Col style={{ padding: 20 }}>
            <h3>Provide the best</h3>
            <h1>Beard Oil For You</h1>
            <p>
              We provide the best Beard oil all over the world. We are the
              worldd best store for Beard Oil. You can buy our product without
              any hegitation because we always consus about our product quality
              and always maintain it properly so your can trust and this is our
              main goal we belive that...
            </p>
            <p>
              Some of our customer say’s that they trust us and buy our product
              without any hagitation because they belive us and always happy
            </p>

            <Button variant="outline-primary">View More</Button>
          </Col>
          <Col>
            <Image
              src="http://nailnail.shop/img/banner/6.png"
              width={600}
              height={353}
              layout="responsive"
            />
          </Col>
        </Row>
      </Container>

      <Container style={{ marginTop: 50 }}>
        <iframe
          width="100%"
          height="700"
          src="https://www.youtube.com/embed/AtAKsF8z1is"
          title="YouTube video player"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        ></iframe>
      </Container>

      <div style={{ background: "#ddd" }}>
        <Container style={{ paddingTop: 50, paddingBottom: 50, marginTop: 50 }}>
          <Row>
            <>
              <Col xs={6}>
                <h3>{year}</h3>
                <p>{data[year].p}</p>
              </Col>
              <Col xs={4} style={{ display: "flex", flex: 1 }}>
                <img
                  src={data[year].image}
                  style={{ flex: 1, width: "386px", height: "347px" }}
                />
              </Col>
            </>
            <Col xs={2}>
              <ul style={{ listStyleType: "none" }}>
                {Object.keys(data).map((y) => (
                  <li
                    style={{
                      color: year === y ? "#09c" : "#000",
                      fontWeight: "bold",
                      paddingTop: 10,
                      paddingBottom: 10,
                      fontSize: 20,
                    }}
                    onClick={() => setYear(y)}
                  >
                    - {y}
                  </li>
                ))}
              </ul>
            </Col>
          </Row>
        </Container>
      </div>

      <Row style={{ padding: 100, maxWidth: "100%" }}>
        <Col style={{ display: "flex", justifyContent: "center" }}>
          <Image
            src="http://nailnail.shop/img/brand-logo/1.png"
            width={83}
            height={82}
            layout="responsive"
          />
        </Col>
        <Col style={{ display: "flex", justifyContent: "center" }}>
          <Image
            src="http://nailnail.shop/img/brand-logo/2.png"
            width={83}
            height={82}
            layout="responsive"
          />
        </Col>
        <Col style={{ display: "flex", justifyContent: "center" }}>
          <Image
            src="http://nailnail.shop/img/brand-logo/3.png"
            width={83}
            height={82}
            layout="responsive"
          />
        </Col>
        <Col style={{ display: "flex", justifyContent: "center" }}>
          <Image
            src="http://nailnail.shop/img/brand-logo/4.png"
            width={83}
            height={82}
            layout="responsive"
          />
        </Col>
        <Col style={{ display: "flex", justifyContent: "center" }}>
          <Image
            src="http://nailnail.shop/img/brand-logo/5.png"
            width={83}
            height={82}
            layout="responsive"
          />
        </Col>
      </Row>

      <Container
        style={{
          background: "#fff",
          boxShadow: "0px 10px 20px rgba(0,0,0,0.3)",
        }}
      >
        <Row>
          <Col>
            <div style={{ display: "flex", flexDirection: "row" }}>
              <div style={{ margin: "auto 10px", background: "#09c8" }}>
                <GoBook />
              </div>

              <div className="home_feature">
                <h4>Oredr Online</h4>
                <p>Free Shipping on Order Over $100</p>
              </div>
            </div>
          </Col>
          <Col>
            <div style={{ display: "flex", flexDirection: "row" }}>
              <div style={{ margin: "auto 10px", background: "#09c8" }}>
                <GoBook />
              </div>

              <div className="home_feature">
                <h4>Oredr Online</h4>
                <p>Free Shipping on Order Over $100</p>
              </div>
            </div>
          </Col>
          <Col>
            <div style={{ display: "flex", flexDirection: "row" }}>
              <div style={{ margin: "auto 10px", background: "#09c8" }}>
                <GoBook />
              </div>

              <div className="home_feature">
                <h4>Oredr Online</h4>
                <p>Free Shipping on Order Over $100</p>
              </div>
            </div>
          </Col>
          <Col>
            <div style={{ display: "flex", flexDirection: "row" }}>
              <div style={{ margin: "auto 10px", background: "#09c8" }}>
                <GoBook />
              </div>
              <div className="home_feature">
                <h4>Worldwide Shipping</h4>
                <p>24/7 h Customer Support</p>
              </div>
            </div>
          </Col>

          <Col>
            <div style={{ display: "flex", flexDirection: "row" }}>
              <div style={{ margin: "auto 10px", background: "#09c8" }}>
                <GoBook />
              </div>
              <div className="home_feature">
                <h4>Payment System</h4>
                <p>Secure Payment System</p>
              </div>
            </div>
          </Col>
        </Row>
      </Container>
    </div>
  );
}
