import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useState } from "react";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { Carousel, Container, Row, Col } from "react-bootstrap";
export default function Home() {
  const [index, setIndex] = useState(0);
  const { t } = useTranslation("common");
  const handleSelect = (selectedIndex, e) => {
    setIndex(selectedIndex);
  };

  const items = [
    {
      image: "http://nailnail.shop/img/banner/6.png",
      caption1: "First slide label",
      caption2: "Nulla vitae elit libero, a pharetra augue mollis interdum.",
    },
    {
      image: "http://nailnail.shop/img/banner/6.png",
      caption1: "2 slide label",
      caption2: "Nulla vitae elit libero, a pharetra augue mollis interdum.",
    },
    {
      image: "http://nailnail.shop/img/banner/6.png",
      caption1: "3 slide label",
      caption2: "Nulla vitae elit libero, a pharetra augue mollis interdum.",
    },
    {
      image: "http://nailnail.shop/img/banner/6.png",
      caption1: "4 slide label",
      caption2: "Nulla vitae elit libero, a pharetra augue mollis interdum.",
    },
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Carousel activeIndex={index} onSelect={handleSelect} interval={6000}>
        {items.map((item, index) => {
          return (
            <Carousel.Item key={index}>
              <div className="w-100" style={{ height: 500 }}>
                <Image
                  src={item.image}
                  alt={item.caption1}
                  layout="fill"
                  quality={50}
                />
              </div>
              <Carousel.Caption>
                <h3>{item.Caption1}</h3>
                <p>{item.caption2}</p>
              </Carousel.Caption>
            </Carousel.Item>
          );
        })}
      </Carousel>

      <Container>
        <Row>
          <Col>
            <div>{t("one")}</div>
          </Col>
          <Col>
            <div>{t("two")}</div>
          </Col>
          <Col>
            <div>{t("three")}</div>
          </Col>
        </Row>
      </Container>
    </div>
  );
}
export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common", "footer"])),
  },
});
